sot-openhrp: StackOfTasks.cpp File Reference
StackOfTasks.cpp File Reference
#include "StackOfTasks.h"
#include <fstream>
#include <string>
#include <dlfcn.h>
#include <sys/time.h>
#include <sot-core/debug.h>
#include <sot-core/exception-abstract.h>
#include <sot-core/exception-task.h>
Defines
#define SOT_CHECK_TIME
#define SOT_DEBUG(x) std::cout
Functions
plugin * create_plugin (istringstream &strm)
static bool admissibleState (StackOfTasks::PluginState state, char admis)
Variables
static std::string HRPname = "OpenHRP"
Define Documentation
#define SOT_CHECK_TIME
#define SOT_DEBUG (x) std::cout
Function Documentation
static bool admissibleState (StackOfTasks::PluginState state, char admis) [static]
Referenced by sot::StackOfTasks::cleanup(), sot::StackOfTasks::setup(), sot::StackOfTasks::sotControlFinishing(), sot::StackOfTasks::sotControlLoop(), and sot::StackOfTasks::~StackOfTasks().
plugin* create_plugin (istringstream & strm)
Variable Documentation
std::string HRPname = "OpenHRP" [static]