# Install script for directory: /home/blue/sot-devel/sot-openhrp/src

# Set the install prefix
IF(NOT DEFINED CMAKE_INSTALL_PREFIX)
  SET(CMAKE_INSTALL_PREFIX "/home/blue/sot-lib")
ENDIF(NOT DEFINED CMAKE_INSTALL_PREFIX)
STRING(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
IF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  IF(BUILD_TYPE)
    STRING(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  ELSE(BUILD_TYPE)
    SET(CMAKE_INSTALL_CONFIG_NAME "DEBUG")
  ENDIF(BUILD_TYPE)
  MESSAGE(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
ENDIF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)

# Set the component getting installed.
IF(NOT CMAKE_INSTALL_COMPONENT)
  IF(COMPONENT)
    MESSAGE(STATUS "Install component: \"${COMPONENT}\"")
    SET(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  ELSE(COMPONENT)
    SET(CMAKE_INSTALL_COMPONENT)
  ENDIF(COMPONENT)
ENDIF(NOT CMAKE_INSTALL_COMPONENT)

# Install shared libraries without execute permission?
IF(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  SET(CMAKE_INSTALL_SO_NO_EXE "1")
ENDIF(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/OpenHRP-3.0.5/Controller/IOserver/robot/HRP2JRL/bin" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp/lib/StackOfTasks.so")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/OpenHRP-3.0.5/Controller/IOserver/robot/HRP2JRL/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp/plugin/TestStackOfTasksV3.py")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/OpenHRP-3.0.5/Controller/IOserver/robot/HRP2JRL/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp/plugin/sotTeleopV3.py")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/OpenHRP-3.0.5/Controller/IOserver/robot/HRP2JRL/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp/plugin/sotTeleopV3nonemodal.py")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/OpenHRP-3.0.5/Controller/IOserver/robot/HRP2JRL/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp/plugin/sotGeometry.py")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/OpenHRP-3.0.5/Controller/IOserver/robot/HRP2JRL/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp/plugin/sotTaskLearning.py")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/OpenHRP-3.0.5/Controller/IOserver/robot/HRP2JRL/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp/plugin/sotWalkTask.py")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/OpenHRP-3.0.5/Controller/IOserver/robot/HRP2JRL/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp/plugin/sotSOTH.py")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/OpenHRP-3.0.5/Controller/IOserver/robot/HRP2JRL/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp/plugin/sotWalkTaskGeometry.py")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/OpenHRP-3.0.5/Controller/IOserver/robot/HRP2JRL/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp/plugin/sot_plugin.py")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/OpenHRP-3.0.5/Controller/IOserver/robot/HRP2JRL/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp/plugin/TestHWPGinSOT.py")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/OpenHRP-3.0.5/Controller/IOserver/robot/HRP2JRL/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp/plugin/TestHWPGinSOT.py")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/OpenHRP-3.0.5/Controller/IOserver/robot/HRP2JRL/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp/plugin/demoBSCWreviewmeeting.py")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/OpenHRP-3.0.5/Controller/IOserver/robot/HRP2JRL/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp/plugin/sotWalkTaskDemoROBOTatCWE.py")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/blue/OpenHRP-3.0.5/Controller/IOserver/robot/HRP2JRL/script" TYPE FILE PERMISSIONS OWNER_READ GROUP_READ WORLD_READ FILES "/home/blue/sot-devel/sot-openhrp/plugin/sotTutorial.py")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

