#!/usr/bin/python

#  Copyright 2011, Florent Lamiraux, CNRS
#
#  This file is part of sot-openhrp.
#  sot-openhrp is free software: you can redistribute it and/or
#  modify it under the terms of the GNU Lesser General Public License
#  as published by the Free Software Foundation, either version 3 of
#  the License, or (at your option) any later version.
#
#  sot-openhrp is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Lesser Public License for more details.  You should have
#  received a copy of the GNU Lesser General Public License along with
#  sot-openhrp. If not, see <http://www.gnu.org/licenses/>.

from omniORB import CORBA
import CosNaming
import sys
from dynamic_graph.corba.dynamicGraph import Interpreter

orb = CORBA.ORB_init (sys.argv, CORBA.ORB_ID)
obj = orb.resolve_initial_references("NameService")
rootContext = obj._narrow(CosNaming.NamingContext)

name = [CosNaming.NameComponent ("openhrp",""),
        CosNaming.NameComponent ("stackOfTasks","")]
obj = rootContext.resolve (name)
client = obj._narrow(Interpreter)

while(1):
    command = ""
    line = ""
    while len(line) == 0 or line[-1] != ';':
        try:
            line = raw_input('dg> ')
        except EOFError:
            print ""
            exit()
        command += line + "\n"
    # remove last ";\n"
    command = command[:-2]
    result = client.python(command)
    if result != "None":
        print result
